version: '3'

services:
  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=shop
      - HTTP_PORT=8080
      - JWT_SIGNING_KEY=hXUpYA3ytv4iEzgr55j1x7atG8n6TBEmA5AMLUlx675LUwiBkJ49cnzg42bHw5K

    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shop" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
